import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import GameExperience from "./components/GameExperience";
import Level from "./components/Level";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen">
        <Canvas
          camera={{
            fov: 45,
            near: 0.1,
            far: 50,
            position: [-4, 3, 6],
          }}
          className=""
        >
          <GameExperience />
          {/* <Level /> */}
        </Canvas>
      </main>
    </>
  );
}
